heat_template_version: 2013-05-23

description: Deploy a CoreOS cluster that tracks the Stable Channel

parameters:
  count:
    description: Number of CoreOS machines to deploy
    type: number
    default: 3
    constraints:
    - range:
        min: 1
        max: 12
      description: Must be between 3 and 12 servers.
  flavor:
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.
  image:
    type: string
    default: CoreOS (Stable)
    constraints:
    - allowed_values:
      - CoreOS (Alpha) # alpha
      - CoreOS (Beta) # beta
      - CoreOS (Stable) # stable
  name:
    type: string
    description: Name of each CoreOS machine booted
    default: CoreOS
  etcd_discovery:
    type: string
    description: URL of etcd discovery
    default: master
  network_range:
    label: Private Network CIDR
    description: Private Network to use for CoreOS Communications
    type: string
    default: 192.168.224.0/20


resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: name }
      save_private_key: true

  coreos_network:
    type: Rackspace::Cloud::Network
    properties:
      label: { get_param: name }
      cidr: { get_param: network_range }

  coreos_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: count }
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_resource: ssh_key }
          image: "513f96f3-20e4-4865-b039-d2ca3944af4e"
          flavor: { get_param: flavor }
          name: { get_param: name }
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          - uuid: { get_resource: coreos_network }
          user_data_format: RAW
          config_drive: "true"
          user_data:
            str_replace:
              template: |
                #cloud-config
                ---
                write_files:
                  - path: /etc/motd
                    content: "CoreOS on RAX"
                  - path: /etc/profile.d/nse-function.sh
                    permissions: 0755
                    content: |
                      function nse() {
                        sudo nsenter --pid --uts --mount --ipc --net --target $(docker inspect --format="{{ .State.Pid }}" $1)
                      }
                  - path:  /etc/iptables.rules
                    permissions: 0600
                    content: |
                      *filter
                      :INPUT DROP [0:0]
                      :FORWARD DROP [0:0]
                      :OUTPUT ACCEPT [0:0]
                      -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
                      -A INPUT -p tcp --dport 22 -j ACCEPT
                      -A INPUT -i lo -j ACCEPT
                      -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
                      -A INPUT -p icmp --icmp-type destination-unreachable -j ACCEPT
                      -A INPUT -p icmp --icmp-type time-exceeded -j ACCEPT
                      -A INPUT -p tcp -i eth0 --dport 4001 -j DROP
                      -A INPUT -p tcp -i eth0 --dport 7001 -j DROP
                      -A INPUT -p tcp -i eth1 --dport 4001 -j DROP
                      -A INPUT -p tcp -i eth1 --dport 7001 -j DROP
                      -A INPUT -i eth0 -j DROP
                      COMMIT
                coreos:
                  etcd:
                    # generate a new token for each unique cluster from https://discovery.etcd.io/new
                    # uncomment the following line and replace it with your discovery URL
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001
                    discovery: %etcd_discovery%
                  fleet:
                  units:
                  - name: etcd.service
                    command: start
                  - name: fleet.service
                    command: start
                  - name: stop-update-engine.service
                    command: start
                    content: |
                      [Unit]
                      Description=stop update-engine
                      [Service]
                      Type=oneshot
                      ExecStart=/usr/bin/systemctl stop update-engine.service
                      ExecStartPost=/usr/bin/systemctl mask update-engine.service
                  - name: firewall.service
                    command: start
                    content: |
                      [Unit]
                      Description=firewall
                      DefaultDependencies=no
                      After=systemd-sysctl.service
                      Before=sysinit.target
                      [Service]
                      Type=oneshot
                      RemainAfterExit=yes
                      ExecStart=/sbin/iptables-restore /etc/iptables.rules
                      ExecReload=/usr/sbin/iptables-restore /etc/iptables.rules
                      ExecStop=/usr/sbin/iptables --flush
                      RemainAfterExit=yes
                      [Install]
                      WantedBy=sysinit.target
                  - name: cadvisor.service
                    command: start
                    content: |
                      [Unit]
                      Description=cadvisor container
                      After=docker.service
                      Requires=docker.service
                      [Service]
                      Restart=always
                      ExecStartPre=-/usr/bin/docker kill cadvisor
                      ExecStartPre=-/usr/bin/docker rm -f cadvisor
                      ExecStartPre=/usr/bin/docker pull google/cadvisor
                      ExecStart=/usr/bin/docker run --name cadvisor --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=4194:4194 google/cadvisor --logtostderr --port=4194
                      ExecStop=/usr/bin/docker stop -t 2 cadvisor                   
              params:
                "%ssh_private_key%": { get_attr: [ssh_key, private_key] }
                "%etcd_discovery%": { get_param: etcd_discovery }

  coreos_loadbalancer:
    type: Rackspace::Cloud::LoadBalancer
    properties:
      name: { get_param: name }
      nodes:
      - addresses: { get_attr: [coreos_nodes, accessIPv4]} # This is where the
                                                       # wiring magic happens
        port: 22
        condition: ENABLED
      protocol: TCP
      port: 22
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4

outputs:
  loadbalancer:
    description: The public IP address of the load balancer
    value: { get_attr: [coreos_loadbalancer, PublicIp]}
  public_ips:
    description: The public IP addresses of coreos nodes
    value: { get_attr: [coreos_nodes, accessIPv4]}
  networks:
    description: The networks of the coreos nodes.
    value: { get_attr: [coreos_nodes, networks]}
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }
